In [1]:
import pandas as pd
import numpy as np
import sys
sys.path.append("../")

import src.soporte as sp


import seaborn as sns
import matplotlib.pyplot as plt
import pickle

import warnings
warnings.filterwarnings("ignore")

In [2]:
# encoding ChestPainType
with open('../data/Pickles/le_encoder.pkl', 'rb') as le:
    encoding_le = pickle.load(le)
    
# encoding ChestPainType
with open('../data/Pickles/oh_transformados.pkl', 'rb') as oh:
    encoding_oh = pickle.load(oh)
    
# encoding ChestPainType
with open('../data/Pickles/ordinal_encoder.pkl', 'rb') as oe:
    encoding_ord = pickle.load(oe)
    
# encoding ChestPainType
with open('../data/Modelo_3/decisionTree_model.pkl', 'rb') as arb:
    arbol = pickle.load(arb)

In [3]:
df_test = pd.read_csv("../data/test.csv").drop("id", axis = 1)
df_test

carat        cut color clarity  depth  table     x     y     z
0       0.32      Ideal     I     SI1   60.5   58.0  4.43  4.49  2.70
1       1.24    Premium     I     SI1   62.9   60.0  6.80  6.74  4.26
2       1.66    Premium     D     SI1   62.0   59.0  7.55  7.60  4.70
3       0.75    Premium     D     SI2   60.6   56.0  5.94  5.90  3.59
4       1.50       Fair     E     SI2   64.8   55.0  7.26  7.15  4.67
...      ...        ...   ...     ...    ...    ...   ...   ...   ...
13480   1.10    Premium     G     SI1   59.6   60.0  6.74  6.70  4.00
13481   0.90  Very Good     D     SI1   62.1   60.0  6.14  6.20  3.83
13482   0.30      Ideal     F     VS2   62.1   53.3  4.30  4.32  2.68
13483   1.25      Ideal     I     SI1   59.6   59.0  7.01  7.09  4.20
13484   0.81    Premium     F     SI1   61.6   58.0  5.96  5.92  3.66

[13485 rows x 9 columns]

In [4]:
# iniciamos el método y aplicamos la transformación a los datos. 
transformados_oe = encoding_ord.transform(df_test[["cut"]])
transformados_oe

array([[0],
       [4],
       [4],
       ...,
       [0],
       [0],
       [4]])

In [5]:
# lo convertimos a dataframe

oe_df =pd.DataFrame(transformados_oe)
oe_df.head()

0
0  0
1  4
2  4
3  4
4  3

In [6]:
df_test["cut_new"] = oe_df
df_test

carat        cut color clarity  depth  table     x     y     z  cut_new
0       0.32      Ideal     I     SI1   60.5   58.0  4.43  4.49  2.70        0
1       1.24    Premium     I     SI1   62.9   60.0  6.80  6.74  4.26        4
2       1.66    Premium     D     SI1   62.0   59.0  7.55  7.60  4.70        4
3       0.75    Premium     D     SI2   60.6   56.0  5.94  5.90  3.59        4
4       1.50       Fair     E     SI2   64.8   55.0  7.26  7.15  4.67        3
...      ...        ...   ...     ...    ...    ...   ...   ...   ...      ...
13480   1.10    Premium     G     SI1   59.6   60.0  6.74  6.70  4.00        4
13481   0.90  Very Good     D     SI1   62.1   60.0  6.14  6.20  3.83        2
13482   0.30      Ideal     F     VS2   62.1   53.3  4.30  4.32  2.68        0
13483   1.25      Ideal     I     SI1   59.6   59.0  7.01  7.09  4.20        0
13484   0.81    Premium     F     SI1   61.6   58.0  5.96  5.92  3.66        4

[13485 rows x 10 columns]

In [7]:
transformados_le = encoding_le.transform(df_test[["color"]])
transformados_le

array([5, 5, 0, ..., 2, 5, 2])

In [8]:
transformados_le = encoding_le.transform(df_test[["color"]])
df_test["color_enco"] = transformados_le
df_test

carat        cut color clarity  depth  table     x     y     z  \
0       0.32      Ideal     I     SI1   60.5   58.0  4.43  4.49  2.70   
1       1.24    Premium     I     SI1   62.9   60.0  6.80  6.74  4.26   
2       1.66    Premium     D     SI1   62.0   59.0  7.55  7.60  4.70   
3       0.75    Premium     D     SI2   60.6   56.0  5.94  5.90  3.59   
4       1.50       Fair     E     SI2   64.8   55.0  7.26  7.15  4.67   
...      ...        ...   ...     ...    ...    ...   ...   ...   ...   
13480   1.10    Premium     G     SI1   59.6   60.0  6.74  6.70  4.00   
13481   0.90  Very Good     D     SI1   62.1   60.0  6.14  6.20  3.83   
13482   0.30      Ideal     F     VS2   62.1   53.3  4.30  4.32  2.68   
13483   1.25      Ideal     I     SI1   59.6   59.0  7.01  7.09  4.20   
13484   0.81    Premium     F     SI1   61.6   58.0  5.96  5.92  3.66   

       cut_new  color_enco  
0            0           5  
1            4           5  
2            4           0  
3            4           0  
4            3           1  
...        ...         ...  
13480        4           3  
13481        2           0  
13482        0           2  
13483        0           5  
13484        4           2  

[13485 rows x 11 columns]

In [9]:
transformados = encoding_oh.transform(df_test[["clarity"]])
transformados

<13485x8 sparse matrix of type '<class 'numpy.float64'>'
	with 13485 stored elements in Compressed Sparse Row format>

In [10]:
oh_df = pd.DataFrame(transformados.toarray(), dtype = int)
oh_df.head()

0  1  2  3  4  5  6  7
0  0  0  1  0  0  0  0  0
1  0  0  1  0  0  0  0  0
2  0  0  1  0  0  0  0  0
3  0  0  0  1  0  0  0  0
4  0  0  0  1  0  0  0  0

In [11]:
oh_df.columns = encoding_oh.get_feature_names_out()
oh_df

clarity_I1  clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  \
0               0           0            1            0            0   
1               0           0            1            0            0   
2               0           0            1            0            0   
3               0           0            0            1            0   
4               0           0            0            1            0   
...           ...         ...          ...          ...          ...   
13480           0           0            1            0            0   
13481           0           0            1            0            0   
13482           0           0            0            0            0   
13483           0           0            1            0            0   
13484           0           0            1            0            0   

       clarity_VS2  clarity_VVS1  clarity_VVS2  
0                0             0             0  
1                0             0             0  
2                0             0             0  
3                0             0             0  
4                0             0             0  
...            ...           ...           ...  
13480            0             0             0  
13481            0             0             0  
13482            1             0             0  
13483            0             0             0  
13484            0             0             0  

[13485 rows x 8 columns]

In [12]:
df_test[oh_df.columns] = oh_df
df_test.drop(["cut", "color", "clarity"], axis = 1, inplace = True)
df_test

carat  depth  table     x     y     z  cut_new  color_enco  clarity_I1  \
0       0.32   60.5   58.0  4.43  4.49  2.70        0           5           0   
1       1.24   62.9   60.0  6.80  6.74  4.26        4           5           0   
2       1.66   62.0   59.0  7.55  7.60  4.70        4           0           0   
3       0.75   60.6   56.0  5.94  5.90  3.59        4           0           0   
4       1.50   64.8   55.0  7.26  7.15  4.67        3           1           0   
...      ...    ...    ...   ...   ...   ...      ...         ...         ...   
13480   1.10   59.6   60.0  6.74  6.70  4.00        4           3           0   
13481   0.90   62.1   60.0  6.14  6.20  3.83        2           0           0   
13482   0.30   62.1   53.3  4.30  4.32  2.68        0           2           0   
13483   1.25   59.6   59.0  7.01  7.09  4.20        0           5           0   
13484   0.81   61.6   58.0  5.96  5.92  3.66        4           2           0   

       clarity_IF  clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  \
0               0            1            0            0            0   
1               0            1            0            0            0   
2               0            1            0            0            0   
3               0            0            1            0            0   
4               0            0            1            0            0   
...           ...          ...          ...          ...          ...   
13480           0            1            0            0            0   
13481           0            1            0            0            0   
13482           0            0            0            0            1   
13483           0            1            0            0            0   
13484           0            1            0            0            0   

       clarity_VVS1  clarity_VVS2  
0                 0             0  
1                 0             0  
2                 0             0  
3                 0             0  
4                 0             0  
...             ...           ...  
13480             0             0  
13481             0             0  
13482             0             0  
13483             0             0  
13484             0             0  

[13485 rows x 16 columns]

In [13]:
arbol.predict(df_test)

array([6.09193333, 8.62276471, 9.46218182, ..., 6.3666875 , 8.8454    ,
       7.96552941])

In [14]:
predict_df = pd.DataFrame(arbol.predict(df_test))
predict_df

0
0      6.091933
1      8.622765
2      9.462182
3      7.813737
4      9.035000
...         ...
13480  8.542800
13481  8.375400
13482  6.366688
13483  8.845400
13484  7.965529

[13485 rows x 1 columns]

In [15]:
predict_df = pd.DataFrame(arbol.predict(df_test))
predict_df = predict_df.rename({0: "price"}, axis = 1).reset_index()
predict_df

index     price
0          0  6.091933
1          1  8.622765
2          2  9.462182
3          3  7.813737
4          4  9.035000
...      ...       ...
13480  13480  8.542800
13481  13481  8.375400
13482  13482  6.366688
13483  13483  8.845400
13484  13484  7.965529

[13485 rows x 2 columns]

In [16]:
predict_df = predict_df.rename({"index": "id"},axis = 1)
predict_df

id     price
0          0  6.091933
1          1  8.622765
2          2  9.462182
3          3  7.813737
4          4  9.035000
...      ...       ...
13480  13480  8.542800
13481  13481  8.375400
13482  13482  6.366688
13483  13483  8.845400
13484  13484  7.965529

[13485 rows x 2 columns]

In [17]:
predict_df.to_csv("../submissions/Submission3.csv", index = False)